project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:

  title: "My Website"

  repo-url: https://github.com/lter/workshop-quarto
  repo-actions: [issue]
  navbar:
    background: primary
    left:
      - text: "Index"
        href: index.qmd
      - text: "Page 1"
        href: page1.qmd
    right: 
      - icon: github

        href: https://github.com/lter/workshop-quarto
  page-footer: 

    center: "Copyright 2025, LTER Network"
    background: secondary

format:
  html:
    toc: true
    link-external-newwindow: true
    link-external-icon: false