project:
  type: website
  execute-dir: project
  output-dir: docs
  render:
    - "*.qmd"

execute: 
  freeze: auto

website:

  title: "Test Website"

  repo-url: https://github.com/rfrelat/webtest
  repo-actions: [issue]

format:
  html:
    toc: true
    link-external-newwindow: true
    link-external-icon: false